apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: consul-medvode-staging
resources:
  - database.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: consul
    newName: rg.fr-par.scw.cloud/djnd/consul-medvode
    newTag: 'c24682a7765dec7db827d30f4db4382ce6dd1ebc'
  # - name: consul-assets
  #   newName: rg.fr-par.scw.cloud/djnd/consul-assets
  #   newTag: 'c24682a7765dec7db827d30f4db4382ce6dd1ebc'
